version: '3'

services:
  dnsrobocert:
    image: adferrand/dnsrobocert
    container_name: dnsrobocert
    volumes:
    - ./data/letsencrypt:/etc/letsencrypt
    - ./data/dnsrobocert:/etc/dnsrobocert
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      email_arg: abc@df.com
      staging_arg: "false"
      domain_args: acb.abc.com
      auth_token: ffY_SafasfZ-bfasdf7o-Aadfafasfpueewrqwerq7M9L42o
    restart: always

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
      - ./data/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    links:
      - v2ray:v2ray #连接v2ray容器，映射主机名，此处非常重要，如果没有这个映射nginx就无法连接v2ray的websocket服务
      - php:docker-php-fpm
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  php:
    image: php:7.2-fpm
    container_name: docker-php-fpm
    restart: unless-stopped
    volumes:
      - ./data/nginx/html:/usr/share/nginx/html
    expose:
      - "9000" #开放端口给容器，不对外开放

  v2ray:
    image: teddysun/v2ray:latest
    container_name: v2ray
    environment:
      - TZ=Asia/Shanghai
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    volumes:
      - ./data/v2ray:/etc/v2ray
      - ./logs/v2ray:/var/log/v2ray
    expose:
      - "23356" #开放端口给容器，不对外开放
