version: '3'

services:
  dnsrobocert:
    image: adferrand/dnsrobocert
    container_name: dnsrobocert
    volumes:
    - ./data/letsencrypt:/etc/letsencrypt
    - ./data/dnsrobocert:/etc/dnsrobocert
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      email_arg: abc@df.com
      staging_arg: "false"
      domain_args: acb.abc.com
      auth_token: ffY_SafasfZ-bfasdf7o-Aadfafasfpueewrqwerq7M9L42o
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
      - ./data/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    links:
      - v2ray:v2ray #连接v2ray容器，映射主机名，此处非常重要，如果没有这个映射nginx就无法连接v2ray的websocket服务
      - xray:xray
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  v2ray:
    image: teddysun/xray:latest
    container_name: v2ray
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - ./data/v2ray:/etc/xray
      - ./logs/v2ray:/var/log/xray
    expose:
      - "23356" #开放端口给容器，不对外开放
      
  xray:
    image: teddysun/xray:latest
    container_name: xray
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - ./data/xray:/etc/xray
      - ./logs/xray:/var/log/xray
    expose:
      - "35625"

  nginxproxymgt:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: npm
    ports:
      - '5680:80'
      - '81:81'
      - '39443:443'
    volumes:
      - ./data/nginx-proxy-manager/data:/data
      - ./data/nginx-proxy-manager/data/letsencrypt:/etc/letsencrypt
