version: '3'

services:
  bitwarden:
   image: bitwardenrs/server
   container_name: bitwarden
   restart: always
   volumes:
    - ./data/bitwarden:/data
   environment:
    WEBSOCKET_ENABLED: "true"
    SIGNUPS_ALLOWED: "true"
    DOMAIN: "https://yourdomain/subpath"
    ADMIN_TOKEN: "fdwer1556445623gwe56456"
   ports:
     - "8080:80"
      
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    links:
      - v2ray:v2ray #连接v2ray容器，映射主机名，此处非常重要，如果没有这个映射nginx就无法连接v2ray的websocket服务
      - php:docker-php-fpm
      - bitwarden:bitwarden
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  php:
    image: php:7.2-fpm
    container_name: docker-php-fpm
    restart: unless-stopped
    volumes:
      - ./data/nginx/html:/usr/share/nginx/html
    expose:
      - "9000" #开放端口给容器，不对外开放
  
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  
  v2ray:
    image: jrohy/v2ray
    container_name: v2ray
    environment:
      - TZ=Asia/Shanghai
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    volumes:
      - ./data/v2ray:/etc/v2ray
      - ./logs/v2ray:/var/log/v2ray
    expose:
      - "23356" #开放端口给容器，不对外开放
